# Generated by Django 5.1 on 2024-09-16 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=20)),
                ('Last_Name', models.CharField(max_length=20)),
                ('Contact', models.IntegerField()),
                ('Email', models.EmailField(max_length=50)),
                ('Age', models.IntegerField()),
            ],
        ),
    ]
