# Generated by Django 5.1 on 2024-09-20 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_student_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='new_image',
            field=models.FileField(default=None, max_length=500, null=True, upload_to='new/'),
        ),
    ]
